@startuml

hide empty description

    [*] --> Git : Added changes in a commit to git

    state pipeline {
        Git --> Started : GitLab moniters a change in git repository
        Started --> ImageBuilt : Builds a Docker image
        ImageBuilt --> StoreImage : Stores image in GitLab
        StoreImage --> RunTests : Image stored, build finished, run tests
        RunTests --> Deploy : Tests successful
    }
    RunTests --> [*] : Tests failed
    ImageBuilt --> [*] : Build failed

    Deploy --> InstallApplication : Install application on kubernetes
    InstallApplication --> [*] : Deployment success
    InstallApplication --> Rollback : Deployment failed
    Rollback --> [*] : Application rolled back

@enduml