@startuml

skinparam monochrome true

package "Domænemodel Converge" {
object User
object Login{
   Email
  Password 
  
  }

object Signup{
   Fornavn
  Efternavn
  Email
 Password 
  }
object Portfolio{
  Name
  Skills
  Experience
  Jobs rating
  }
object Categories{
  Name
  }
object PostProject{
  Project title
  Category
  Subcategory
  Description
  UploadFil
  workType
  }
object Projects
object Chat{
  Messages
  }
object Files
object Payments{
  Balance
  Amount
  Deposit
  Withdraw
  }
object Search
object Dashboard


User --> Login: Has a
User --> Signup: Can
User --> Portfolio: Has  a 
User --> Categories: Can choose
User --> PostProject: can 
User --> Project: Can take 
User --> Chat: Sends / resieves messages
User --> Files: Can upload a file
User --> Payments: can
User --> Search: Can search a job 
  


Login --> Dashboard: Access to
Dashboard --> Portfolio:  Acces to
Dashboard --> Chat:  Acces to
Dashboard --> Files:  Acces to
Dashboard --> Projects:  Acces to
Dashboard --> Categories: Acces to
Dashboard --> Payments:  Acces to
Dashboard --> Search:  Acces to
Dashboard --> PostProject:  Acces to
  
}

@enduml