@startuml

skinparam monochrome true
skinparam componentStyle uml2
left to right direction 


package "Komponent diagram" as ma{
folder "Presentation" as ts{
  
[Login]
[Signup]
[Search]
[portfolio]
[Chat]
[Dashboard]
[Settings]
[Categories]
[Payments]
[Files]
[Projects]
  
}


cloud {
  
  [Userservice] -up- userAPI
  [SearchService] -up- searchAPI
  [PortfolioService] -up- portfolioAPI
  [ChatService] -up- chatAPI
  [DashboardService] -up- dashboardAPI 
  [SettingsService] -up-  settingsAPI
  [CategoriesService] -up- categoriesAPI
  [PaymentsService] -up- paymentsAPI
  [FilesService] -up- videochatAPI
  [ProjectsService] -up- ProjectsAPI
  
  
  }

  [Login] --( userAPI
  [Signup] --( userAPI
  [Search] --( searchAPI
  [portfolio] --(  portfolioAPI
  [Chat] --( chatAPI
  [Dashboard] -( dashboardAPI 
  [Settings] -( settingsAPI
  [Categories] -( categoriesAPI
  [Payments] -( paymentsAPI
  [Files] -( videochatAPI
  [Projects] -( ProjectsAPI
  
  
  [Userservice] --> [User persistering]
  [SearchService] --> [Search persistering]
  [PortfolioService] --> [Portfolio persistering]
  [ChatService] --> [Chat persistering]
  [DashboardService] --> [Dashboard persistering]
  [SettingsService] --> [Settings persistering]
  [CategoriesService] --> [Categories persistering]
  [PaymentsService] --> [Payments persistering]
  [FilesService] --> [Files persistering]
  [ProjectsService] --> [Projects persistering]
  

}

@enduml