@startuml
hide footbox
autonumber "<b>[0]"
skinparam monochrome true

actor Freelancer
participant BiddingService

activate Freelancer
Freelancer -> BiddingService: Bid on a project

activate BiddingService
BiddingService -> BiddingService: Create a bid
BiddingService --> Freelancer: Confirms bid is created
@enduml