@startuml
hide footbox
autonumber "<b>[0]"
skinparam monochrome true

actor Freelancer
participant CollaborationService

activate Freelancer
Freelancer -> CollaborationService: Receive matrial

activate CollaborationService
CollaborationService -> CollaborationService: Checking the matrial
CollaborationService --> Freelancer: Confirms matrial is received

@enduml